In [ ]:
#checking whether the patient has diabetes or not using classifier model

importing libraries

In [ ]:
import numpy as np
import pandas as pd
#for pre processing the data(standardise data in common range)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
#support vector machine-->svm
from sklearn.metrics import accuracy_score

data collection and analysis

In [ ]:
diabetes_dataset=pd.read_csv("/content/diabetes.csv")

In [ ]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
diabetes_dataset.shape

(768, 9)

In [ ]:
x=diabetes_dataset.drop(columns ='Outcome',axis=1)

In [ ]:
y=diabetes_dataset['Outcome']

In [ ]:
#axis=1 to drop column
#axis=0 to drop a row

In [ ]:
diabetes_dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

data standardisation

In [ ]:
#different columns are of different range,this will be difficult for the model to make predictions
#make them all in a same range by standardising thrm

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
standardised_data=scaler.transform(x)

In [ ]:
#instead of doing fit and transform seperately, sacler.fit_tranform() function can be used

In [ ]:
standardised_data


array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
x=standardised_data

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.2,random_state=2,stratify=y)

In [ ]:
#random state = splitting of two(for replicating)

In [ ]:
x.shape

(768, 8)

In [ ]:
x_train.shape

(153, 8)

(153, 8)

In [ ]:
x_test.shape

(615, 8)

(615, 8)

training the model

In [ ]:
classifier=svm.SVC(kernel='linear')
#support vector machine classifier

In [ ]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

evaluating the model

In [ ]:
x_train_prediction=classifier.predict(x_train)
x_train_accuracy=accuracy_score(x_train_prediction,y_train)

In [ ]:
x_train_accuracy

0.7843137254901961

In [ ]:
x_test_prediction=classifier.predict(x_test)
x_test_accuracy=accuracy_score(x_test_prediction,y_test)

In [ ]:
x_test_accuracy

0.7495934959349594

In [ ]:
#overfitting-->accuarcy of train data is more than that of test data

predictive system

In [ ]:
input_data=(5,166,72,19,175,25.8,0.587,51)
input_data_np_array=np.asarray(input_data)
input_data_reshaped=input_data_np_array.reshape(1,-1)
#reshape-->saying the machine that we dont need you to predict for all 768 rows...the input is jus 1
#do standardisation
std_data=scaler.transform(input_data_reshaped)
#only transforming is enough...coz...already fitted

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
prediction=classifier.predict(std_data)

In [ ]:
prediction

array([0])

In [ ]:
if(prediction[0]==0):
  print("Sorry! you have diabetes")
else:
  print("Relax! you dont have diabetes")

Sorry! you have diabetes


In [ ]:
prediction

array([0])

In [ ]:
input_data=(7,196,90,0,0,39.8,0.451,41)
input_data_np_array=np.asarray(input_data)
input_data_reshaped=input_data_np_array.reshape(1,-1)
#reshape-->saying the machine that we dont need you to predict for all 768 rows...the input is jus 1
#do standardisation
std_data=scaler.transform(input_data_reshaped)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
prediction

array([0])

In [ ]:
std_data

array([[ 0.93691372,  2.35058677,  1.08020025, -1.28821221, -0.69289057,
         0.99091209, -0.06304891,  0.66020563]])

In [ ]:
prediction

array([0])